name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: jr200-labs/github-action-templates/.github/workflows/release_please.yaml@master
    with:
      release-type: simple
      target-branch: master
    secrets:
      app_private_key: ${{ secrets.INTEGRATION_APP_PRIVATE_KEY }}
